[abaumannii]
genus = "Acinetobacter.*"
species = "baumannii.*"

[afumigatus] # NOT FOUND IN GTDB
genus = "Aspergillus.*"
species = "afumigatus.*"

[aphagocytophilum]
genus = "Anaplasma.*"
species = "phagocytophilum.*"

[bburgdorferi]
genus = "Borreliella.*"
species = "burgdorferi.*"

[bcc]
genus = "Burkholderia.*"
species = "cepacia.*"

[bcereus]
genus = "Bacillus.*"
species = "cereus.*"

[bhampsonii]
genus = "Brachyspira.*"
species = "hampsonii.*"

[bhenselae]
genus = "Bartonella.*"
species = "henselae.*"

[bhyodysenteriae]
genus = "Brachyspira.*"
species = "hyodysenteriae.*"

[bifidobacterium]
genus = "Bifidobacterium.*"
species = "bifidum.*"

[bintermedia]
genus = "Brachyspira.*"
species = "intermedia.*"

[blicheniformis]
genus = "Bacillus.*"
species = "licheniformis.*"

[bordetella]
genus = "Bordetella.*"
species = "pertussis.*"

[bpilosicoli]
genus = "Brachyspira.*"
species = "pilosicoli.*"

[bpseudomallei]
genus = "Burkholderia.*"
species = "pseudomallei.*"

[bsubtilis]
genus = "Bacillus.*"
species = "subtilis.*"

[calbicans] # NOT FOUND IN GTDB
genus = "Candida.*"
species = "albicans.*"

[campylobacter]
genus = "Campylobacter.*"
species = "(coli|jejuni).*"

[cbotulinum]
genus = "Clostridium.*"
species = "botulinum.*"

[cconcisus]
genus = "Campylobacter.*"
species = "concisus.*"

[cdifficile]
genus = "(Clostridium|Peptoclostridium).*"
species = "difficile.*"

[cdiphtheriae]
genus = "Corynebacterium.*"
species = "diphtheriae.*"

[cfetus]
genus = "Campylobacter.*"
species = "fetus.*"

[cfreundii]
genus = "Citrobacter.*"
species = "freundii.*"

[cglabrata]
genus = "Candida.*"
species = "glabrata.*"

[chelveticus]
genus = "Campylobacter.*"
species = "helveticus.*"

[chyointestinalis]
genus = "Campylobacter.*"
species = "hyointestinalis.*"

[cinsulaenigrae]
genus = "Campylobacter.*"
species = "insulaenigrae.*"

[ckrusei]
genus = "Candida.*"
species = "krusei.*"

[clanienae]
genus = "Campylobacter.*"
species = "lanienae.*"

[clari]
genus = "Campylobacter.*"
species = "lari.*"

[cmaltaromaticum]
genus = "Carnobacterium.*"
species = "maltaromaticum.*"

[cneoformans]
genus = "Cryptococcus.*"
species = "neoformans.*"

[csepticum]
genus = "Clostridium.*"
species = "septicum.*"

[csinensis]
genus = "Clonorchis.*"
species = "sinensis.*"

[csputorum]
genus = "Campylobacter.*"
species = "sputorum.*"

[ctropicalis]
genus = "Candida.*"
species = "tropicalis.*"

[cupsaliensis]
genus = "Campylobacter.*"
species = "upsaliensis.*"

[ecloacae]
genus = "Enterobacter.*"
species = "cloacae.*"

[edwardsiella]
genus = "Edwardsiella.*"
species = "tarda.*"

[efaecalis]
genus = "Enterococcus.*"
species = "faecalis.*"

[efaecium]
genus = "Enterococcus.*"
species = "faecium.*"

[fpsychrophilum]
genus = "Flavobacterium.*"
species = "psychrophilum.*"

[hcinaedi]
genus = "Helicobacter.*"
species = "cinaedi.*"

[hinfluenzae]
genus = "Haemophilus.*"
species = "influenzae.*"

[hparasuis]
genus = "Haemophilus.*"
species = "parasuis.*"

[hpylori]
genus = "Helicobacter.*"
species = "pylori.*"

[hsuis]
genus = "Haematopinus.*"
species = "suis.*"

[kkingae]
genus = "Kingella.*"
species = "kingae.*"

[koxytoca]
genus = "Klebsiella.*"
species = "oxytoca.*"

[kpneumoniae]
genus = "Klebsiella.*"
species = "pneumoniae.*"

[kseptempunctata]
genus = "Kudoa.*"
species = "septempunctata.*"

[lcasei]
genus = "Lactobacillus.*"
species = "casei.*"

[lmonocytogenes]
genus = "Listeria.*"
species = "monocytogenes.*"

[lsalivarius]
genus = "Lactobacillus.*"
species = "salivarius.*"

[mabscessus]
genus = "Mycobacterium.*"
species = "abscessus.*"

[magalactiae]
genus = "Mycoplasma.*"
species = "agalactiae.*"

[mbovis]
genus = "Mycoplasma.*"
species = "bovis.*"

[mcatarrhalis]
genus = "Moraxella.*"
species = "catarrhalis.*"

[mhaemolytica]
genus = "Mannheimia.*"
species = "haemolytica.*"

[mhyorhinis]
genus = "Mycoplasma.*"
species = "hyorhinis.*"

[mmassiliense]
genus = "Mycobacterium.*"
species = "massiliense.*"

[mplutonius]
genus = "Melissococcus.*"
species = "plutonius.*"

[orhinotracheale]
genus = "Ornithobacterium.*"
species = "rhinotracheale.*"

[otsutsugamushi]
genus = "Orientia.*"
species = "tsutsugamushi.*"

[pacnes]
genus = "Propionibacterium.*"
species = "acnes.*"

[paeruginosa]
genus = "Pseudomonas.*"
species = "aeruginosa.*"

[pagglomerans]
genus = "Pantoea.*"
species = "agglomerans.*"

[pfluorescens]
genus = "Pseudomonas.*"
species = "fluorescens.*"

[pfreudenreichii]
genus = "Propionibacterium.*"
species = "freudenreichii.*"

[pgingivalis]
genus = "Porphyromonas.*"
species = "gingivalis.*"

[plarvae]
genus = "Paenibacillus.*"
species = "larvae.*"

[pmultocida_multihost]
genus = "Pasteurella.*"
species = "multocida.*"

[pmultocida_rirdc]
genus = "Pasteurella.*"
species = "multocida.*"

[ppentosaceus]
genus = "Pediococcus.*"
species = "pentosaceus.*"

[pshigelloides]
genus = "Plesiomonas.*"
species = "shigelloides.*"

[ranatipestifer]
genus = "Riemerella.*"
species = "anatipestifer.*"

[sagalactiae]
genus = "Streptococcus.*"
species = "agalactiae.*"

[saureus]
genus = "Staphylococcus.*"
species = "aureus.*"

[scanis]
genus = "Streptococcus.*"
species = "canis.*"

[sdysgalactiae]
genus = "Streptococcus.*"
species = "dysgalactiae.*"

[senterica]
genus = "Salmonella.*"
species = "enterica.*"

[sepidermidis]
genus = "Staphylococcus.*"
species = "epidermidis.*"

[sgallolyticus]
genus = "Streptococcus.*"
species = "gallolyticus.*"

[shaemolyticus]
genus = "Staphylococcus.*"
species = "haemolyticus.*"

[shominis]
genus = "Stapylococcus.*"
species = "hominis.*"

[slugdunensis]
genus = "Staphylococcus.*"
species = "lugdunensis.*"

[smaltophilia]
genus = "Stenotrophomonas.*"
species = "maltophilia.*"

[soralis]
genus = "Streptococcus.*"
species = "oralis.*"

[spneumoniae]
genus = "Streptococcus.*"
species = "pneumoniae.*"

[spseudintermedius]
genus = "Staphylococcus.*"
species = "pseudintermedius.*"

[spyogenes]
genus = "Streptococcus.*"
species = "pyogenes.*"

[ssuis]
genus = "Streptococcus.*"
species = "suis.*"

[sthermophilus]
genus = "Streptococcus.*"
species = "thermophilus.*"

[suberis]
genus = "Streptococcus.*"
species = "uberis.*"

[szooepidemicus]
genus = "Streptococcus.*"
species = "equi.*"

[tenacibaculum]
genus = "Tenacibaculum.*"

[tvaginalis]
genus = "Trichomonas.*"
species = "vaginalis.*"

[vcholerae]
genus = "Vibrio.*"
species = "cholerae.*"

[vparahaemolyticus]
genus = "Vibrio.*"
species = "parahaemolyticus.*"

[vtapetis]
genus = "Vibrio.*"
species = "tapetis.*"

[vvulnificus]
genus = "Vibrio.*"
species = "vulnificus.*"

[xfastidiosa]
genus = "Xylella.*"
species = "fastidiosa.*"

[ypseudotuberculosis]
genus = "Yersinia.*"
species = "pseudotuberculosis.*"

[yruckeri]
genus = "Yersinia.*"
species = "ruckeri.*"

# remaining are mapped per genus
[achromobacter]
genus = "Achromobacter.*"

[aeromonas]
genus = "Aeromonas.*"

[arcobacter]
genus = "Arcobacter.*"

[borrelia]
genus = "Borrelia.*"

[brachyspira]
genus = "Brachyspira"

[chlamydiales]
genus = "Chlamydia"

[cronobacter]
genus = "Cronobacter"

[ecoli]
genus = "Escherichia|Shigella"

[haemophilus]
genus = "Haemophilus"

[legionella]
genus = "Legionella"

[leptospira]
genus = "Leptospira"

[neisseria]
genus = "Neisseria"

[sinorhizobium]
genus = "Sinorhizobium"

[streptomyces]
genus = "Streptomyces"

[taylorella]
genus = "Taylorella"

[vibrio]
genus = "Vibrio"

[wolbachia]
genus = "Wolbachia"

[yersinia]
genus = "Yersinia"
