from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"
include: "rules/reads.smk"
include: "rules/unicycler.smk"
include: "rules/check_post_assembly.smk"
include: "rules/check_pre_assembly.smk"
include: "rules/selfcontamination_check.smk"


if not config["gtdb_hack"]:

    include: "rules/gtdb.smk"
    include: "rules/amrdetect.smk"


rule all:
    input:
        **get_outputs(),
    localrule: True


onsuccess:
    if os.path.exists("localDB"):
        print("Cleaning up loaded RGI database...", file=sys.stderr)
        shell("rm -rf localDB")
