from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,


include: "rules/common.smk"
include: "rules/reads.smk"
include: "rules/genera_check.smk"
include: "rules/multiqc.smk"
include: "rules/unicycler.smk"
include: "rules/check.smk"


rule all:
    input:
        **get_outputs(),
