from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"
include: "rules/reads.smk"
include: "rules/unicycler.smk"
include: "rules/check_post_assembly.smk"
include: "rules/check_pre_assembly.smk"
include: "rules/selfcontamination_check.smk"
include: "rules/hamronization.smk"
include: "rules/summary.smk"
include: "rules/gtdb.smk"
include: "rules/amrdetect.smk"
include: "rules/insilico.smk"

if config["mlst_custom"]["db_dir"] is not None:
    include: "rules/mlst_custom.smk"

rule all:
    input:
        **get_outputs(),
    localrule: True


onsuccess:
    if os.path.exists("localDB"):
        logger.info("Cleaning up loaded RGI database...")
        shell("rm -rf localDB")
