name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.0
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: .tests
          snakefile: workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--keep-going --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
          show-disk-usage-on-error: true

      # - name: Test report
      #   uses: snakemake/snakemake-github-action@v1.25.1
      #   with:
      #     directory: .tests
      #     snakefile: workflow/Snakefile
      #     args: "--report report.zip"
      #     show-disk-usage-on-error: true
